/** Common working diagnoses offered as autocomplete in the consult screen. */
export const DIAGNOSIS_SUGGESTIONS = [
  "Rheumatoid arthritis (M06.9)",
  "Osteoarthritis of knee (M17.9)",
  "Osteoarthritis of hip (M16.9)",
  "Ankylosing spondylitis (M45)",
  "Low back pain (M54.5)",
  "Cervical spondylosis (M47.812)",
  "Gout, unspecified (M10.9)",
  "Fibromyalgia (M79.7)",
  "Systemic lupus erythematosus (M32.9)",
  "Psoriatic arthritis (L40.50)",
  "Reactive arthritis (M02.9)",
  "Sjögren syndrome (M35.0)",
  "Osteoporosis, unspecified (M81.0)",
  "Frozen shoulder / adhesive capsulitis (M75.0)",
  "Carpal tunnel syndrome (G56.0)",
  "Sciatica (M54.3)",
  "Cervical myofascial pain syndrome (M79.1)",
  "Juvenile idiopathic arthritis (M08.9)",
  "Polymyalgia rheumatica (M35.3)",
  "Vitamin D deficiency (E55.9)",
];
